from __future__ import annotations

from copy import deepcopy
from typing import Any

from .metric_contract import METRIC_DEFINITION_VERSION

METRIC_REGISTRY_V1_VERSION = "2026.03-v2"


def _metric(
    *,
    metric_id: str,
    display_name: str,
    category: str,
    executive_description: str,
    minimum_datasets: list[str],
    ideal_datasets: list[str],
    minimum_fields: list[str],
    supported_scopes: list[str],
    formula_engine: str,
    fallback_strategy: str,
    blockers: list[str],
    confidence_rule: str,
    decision_grade_rule: str,
    output_unit: str,
    output_format: str,
    missing_data_message: str,
) -> dict[str, Any]:
    return {
        "metric_id": metric_id,
        "display_name": display_name,
        "category": category,
        "executive_description": executive_description,
        "minimum_datasets": minimum_datasets,
        "ideal_datasets": ideal_datasets,
        "minimum_fields": minimum_fields,
        "supported_scopes": supported_scopes,
        "formula_engine": formula_engine,
        "fallback_strategy": fallback_strategy,
        "blockers": blockers,
        "confidence_rule": confidence_rule,
        "decision_grade_rule": decision_grade_rule,
        "output_unit": output_unit,
        "output_format": output_format,
        "missing_data_message": missing_data_message,
        "metric_definition_version": METRIC_DEFINITION_VERSION,
    }


METRIC_REGISTRY: dict[str, dict[str, Any]] = {
    # Operacional
    "production_volume": _metric(
        metric_id="production_volume",
        display_name="Volume de producao",
        category="operacional",
        executive_description="Consolida o total produzido no escopo selecionado.",
        minimum_datasets=["production"],
        ideal_datasets=["production"],
        minimum_fields=["produced_quantity"],
        supported_scopes=["global", "monthly", "product"],
        formula_engine="sum(production.produced_quantity)",
        fallback_strategy="unavailable_without_production",
        blockers=["production_missing"],
        confidence_rule="high_with_consistent_volume_and_rows",
        decision_grade_rule="A_if_ready_high_confidence",
        output_unit="kg",
        output_format="number",
        missing_data_message="Sem historico de producao para consolidar volume operacional.",
    ),
    "production_trend": _metric(
        metric_id="production_trend",
        display_name="Tendencia de producao",
        category="operacional",
        executive_description="Compara ciclos recentes de producao para identificar aceleracao ou desaceleracao.",
        minimum_datasets=["production"],
        ideal_datasets=["production"],
        minimum_fields=["produced_quantity", "month", "reference_year"],
        supported_scopes=["global", "monthly", "product"],
        formula_engine="compare_recent_periods(production)",
        fallback_strategy="use_shorter_window_if_history_is_small",
        blockers=["production_missing"],
        confidence_rule="high_with_6plus_periods_medium_with_3plus",
        decision_grade_rule="A_or_B_when_trend_supported_by_history",
        output_unit="%",
        output_format="percent",
        missing_data_message="Historico temporal insuficiente para tendencia de producao robusta.",
    ),
    "operational_seasonality": _metric(
        metric_id="operational_seasonality",
        display_name="Sazonalidade operacional",
        category="operacional",
        executive_description="Mede variabilidade temporal da producao para suportar planejamento.",
        minimum_datasets=["production"],
        ideal_datasets=["production"],
        minimum_fields=["produced_quantity", "month", "reference_year"],
        supported_scopes=["global", "product"],
        formula_engine="cv(monthly_production)",
        fallback_strategy="partial_with_limited_months",
        blockers=["production_missing"],
        confidence_rule="high_with_12plus_periods",
        decision_grade_rule="A_or_B_when_variability_is_stable",
        output_unit="%",
        output_format="percent",
        missing_data_message="Sem base mensal suficiente para leitura de sazonalidade.",
    ),
    "abc_operational": _metric(
        metric_id="abc_operational",
        display_name="ABC operacional",
        category="operacional",
        executive_description="Indica concentracao de volume nos SKUs de maior relevancia operacional.",
        minimum_datasets=["production"],
        ideal_datasets=["production"],
        minimum_fields=["product_code", "produced_quantity"],
        supported_scopes=["global", "product"],
        formula_engine="top20_share_by_product(production)",
        fallback_strategy="partial_with_low_product_coverage",
        blockers=["production_missing"],
        confidence_rule="high_when_product_distribution_is_representative",
        decision_grade_rule="A_if_top_share_and_data_quality_ready",
        output_unit="%",
        output_format="percent",
        missing_data_message="Sem dados suficientes para classificar concentracao ABC operacional.",
    ),
    "xyz_operational": _metric(
        metric_id="xyz_operational",
        display_name="XYZ operacional",
        category="operacional",
        executive_description="Mede estabilidade da demanda/operacao por SKU a partir da variabilidade.",
        minimum_datasets=["production"],
        ideal_datasets=["production"],
        minimum_fields=["product_code", "produced_quantity", "month", "reference_year"],
        supported_scopes=["global", "product"],
        formula_engine="cv_by_product_and_classify_xyz",
        fallback_strategy="partial_without_full_month_window",
        blockers=["production_missing"],
        confidence_rule="high_with_6plus_months_per_relevant_sku",
        decision_grade_rule="A_or_B_when_distribution_is_consistent",
        output_unit="%",
        output_format="percent",
        missing_data_message="Sem dados suficientes para leitura de estabilidade XYZ operacional.",
    ),
    "operational_risk": _metric(
        metric_id="operational_risk",
        display_name="Risco operacional",
        category="operacional",
        executive_description="Score de risco operacional considerando tendencia e variabilidade.",
        minimum_datasets=["production"],
        ideal_datasets=["production", "sales_orders"],
        minimum_fields=["produced_quantity"],
        supported_scopes=["global", "product"],
        formula_engine="risk_score_from_trend_and_variability",
        fallback_strategy="partial_with_single_source_production",
        blockers=["production_missing"],
        confidence_rule="medium_to_high_when_inputs_trend_and_variability_exist",
        decision_grade_rule="A_if_low_risk_high_confidence",
        output_unit="score",
        output_format="number",
        missing_data_message="Sem base operacional para estimar risco de execucao.",
    ),
    # Comercial
    "sales_volume": _metric(
        metric_id="sales_volume",
        display_name="Volume vendido",
        category="comercial",
        executive_description="Consolida o volume vendido/pedido no escopo selecionado.",
        minimum_datasets=["sales_orders"],
        ideal_datasets=["sales_orders"],
        minimum_fields=["order_quantity"],
        supported_scopes=["global", "monthly", "product", "customer"],
        formula_engine="sum(sales_orders.order_quantity)",
        fallback_strategy="unavailable_without_sales_orders",
        blockers=["sales_orders_missing"],
        confidence_rule="high_with_consistent_order_rows",
        decision_grade_rule="A_if_ready_high_confidence",
        output_unit="kg",
        output_format="number",
        missing_data_message="Sem carteira de vendas/pedidos para consolidar volume comercial.",
    ),
    "sales_growth": _metric(
        metric_id="sales_growth",
        display_name="Crescimento comercial",
        category="comercial",
        executive_description="Compara ciclos de vendas recentes para identificar aceleracao comercial.",
        minimum_datasets=["sales_orders"],
        ideal_datasets=["sales_orders"],
        minimum_fields=["order_date", "order_quantity"],
        supported_scopes=["global", "monthly", "customer", "product"],
        formula_engine="compare_recent_periods(sales_orders)",
        fallback_strategy="partial_with_short_history",
        blockers=["sales_orders_missing"],
        confidence_rule="high_with_6plus_periods_medium_with_3plus",
        decision_grade_rule="A_or_B_when_growth_supported_by_history",
        output_unit="%",
        output_format="percent",
        missing_data_message="Historico de vendas insuficiente para crescimento comercial robusto.",
    ),
    "customer_mix": _metric(
        metric_id="customer_mix",
        display_name="Mix de clientes",
        category="comercial",
        executive_description="Mede participacao dos principais clientes no volume comercial.",
        minimum_datasets=["sales_orders"],
        ideal_datasets=["sales_orders", "customers"],
        minimum_fields=["customer_code", "order_quantity"],
        supported_scopes=["global", "customer"],
        formula_engine="top_customer_share(sales_orders)",
        fallback_strategy="fallback_to_customer_name_if_code_missing",
        blockers=["sales_orders_missing"],
        confidence_rule="high_with_customer_code_coverage",
        decision_grade_rule="A_if_mix_representative",
        output_unit="%",
        output_format="percent",
        missing_data_message="Sem dados de cliente para leitura de mix comercial.",
    ),
    "product_mix": _metric(
        metric_id="product_mix",
        display_name="Mix de produtos",
        category="comercial",
        executive_description="Mede participacao dos SKUs no volume comercial.",
        minimum_datasets=["sales_orders"],
        ideal_datasets=["sales_orders"],
        minimum_fields=["product_code", "order_quantity"],
        supported_scopes=["global", "product"],
        formula_engine="top_product_share(sales_orders)",
        fallback_strategy="none",
        blockers=["sales_orders_missing"],
        confidence_rule="high_with_product_code_coverage",
        decision_grade_rule="A_if_mix_representative",
        output_unit="%",
        output_format="percent",
        missing_data_message="Sem dados por SKU para leitura de mix de produtos.",
    ),
    "sales_concentration": _metric(
        metric_id="sales_concentration",
        display_name="Concentracao comercial",
        category="comercial",
        executive_description="Indice de concentracao da carteira comercial por cliente.",
        minimum_datasets=["sales_orders"],
        ideal_datasets=["sales_orders", "customers"],
        minimum_fields=["customer_code", "order_quantity"],
        supported_scopes=["global", "customer"],
        formula_engine="hhi(customer_share)",
        fallback_strategy="fallback_to_customer_name_if_code_missing",
        blockers=["sales_orders_missing"],
        confidence_rule="high_with_broad_customer_distribution",
        decision_grade_rule="A_if_concentration_with_quality_signal",
        output_unit="hhi",
        output_format="number",
        missing_data_message="Sem dados de carteira para calcular concentracao comercial.",
    ),
    "abc_commercial": _metric(
        metric_id="abc_commercial",
        display_name="ABC comercial",
        category="comercial",
        executive_description="Participacao dos produtos lideres na carteira comercial.",
        minimum_datasets=["sales_orders"],
        ideal_datasets=["sales_orders"],
        minimum_fields=["product_code", "order_quantity"],
        supported_scopes=["global", "product"],
        formula_engine="top20_share_by_product(sales_orders)",
        fallback_strategy="none",
        blockers=["sales_orders_missing"],
        confidence_rule="high_when_product_distribution_is_representative",
        decision_grade_rule="A_if_top_share_with_quality_signal",
        output_unit="%",
        output_format="percent",
        missing_data_message="Sem base comercial para classificar concentracao ABC.",
    ),
    # S&OP integrado
    "demand_vs_operation_gap": _metric(
        metric_id="demand_vs_operation_gap",
        display_name="Gap demanda x operacao",
        category="sop_integrado",
        executive_description="Compara volume demandado e capacidade/volume operacional realizado.",
        minimum_datasets=["production", "sales_orders"],
        ideal_datasets=["production", "sales_orders"],
        minimum_fields=["produced_quantity", "order_quantity"],
        supported_scopes=["global", "monthly", "product"],
        formula_engine="(sales_volume-production_volume)/sales_volume",
        fallback_strategy="partial_if_only_one_side_available",
        blockers=["production_missing", "sales_orders_missing"],
        confidence_rule="high_when_both_sources_ready",
        decision_grade_rule="A_if_gap_small_and_confidence_high",
        output_unit="%",
        output_format="percent",
        missing_data_message="Sem dados integrados de demanda e operacao para calcular gap.",
    ),
    "service_risk": _metric(
        metric_id="service_risk",
        display_name="Risco de atendimento",
        category="sop_integrado",
        executive_description="Score de risco de servico combinando gap e sinais de cobertura.",
        minimum_datasets=["production", "sales_orders"],
        ideal_datasets=["production", "sales_orders", "raw_material_inventory"],
        minimum_fields=["produced_quantity", "order_quantity"],
        supported_scopes=["global", "product"],
        formula_engine="service_risk_from_gap_and_coverage",
        fallback_strategy="partial_without_inventory_signal",
        blockers=["production_missing", "sales_orders_missing"],
        confidence_rule="high_with_gap_plus_inventory",
        decision_grade_rule="A_if_low_risk_with_high_confidence",
        output_unit="score",
        output_format="number",
        missing_data_message="Sem dados integrados suficientes para risco de atendimento.",
    ),
    "mts_mto_recommendation": _metric(
        metric_id="mts_mto_recommendation",
        display_name="Recomendacao MTS/MTO",
        category="sop_integrado",
        executive_description="Recomendacao executiva de politica de atendimento com base no gap e estabilidade.",
        minimum_datasets=["production", "sales_orders"],
        ideal_datasets=["production", "sales_orders", "bom", "raw_material_inventory"],
        minimum_fields=["produced_quantity", "order_quantity"],
        supported_scopes=["global", "product"],
        formula_engine="heuristic_policy_recommendation",
        fallback_strategy="textual_recommendation_with_limited_inputs",
        blockers=["production_missing", "sales_orders_missing"],
        confidence_rule="high_with_integrated_operational_and_supply_signals",
        decision_grade_rule="A_or_B_when_recommendation_supported_by_inputs",
        output_unit="policy",
        output_format="text",
        missing_data_message="Sem base integrada para recomendar politica MTS/MTO com confianca.",
    ),
    "scenario_priority": _metric(
        metric_id="scenario_priority",
        display_name="Priorizacao de cenario",
        category="sop_integrado",
        executive_description="Indica qual frente executiva deve ser priorizada no ciclo atual.",
        minimum_datasets=["production", "sales_orders"],
        ideal_datasets=["production", "sales_orders", "raw_material_inventory", "finance_documents"],
        minimum_fields=["produced_quantity", "order_quantity"],
        supported_scopes=["global"],
        formula_engine="highest_risk_dimension_selector",
        fallback_strategy="prioritize_available_dimension",
        blockers=["production_missing", "sales_orders_missing"],
        confidence_rule="high_with_multidimensional_inputs",
        decision_grade_rule="A_or_B_when_priority_supported_by_scores",
        output_unit="priority",
        output_format="text",
        missing_data_message="Sem base integrada suficiente para priorizar cenario decisorio.",
    ),
    # Materia-prima / supply
    "raw_material_coverage": _metric(
        metric_id="raw_material_coverage",
        display_name="Cobertura de materia-prima",
        category="supply",
        executive_description="Dias medios de cobertura de materia-prima com base em estoque e consumo.",
        minimum_datasets=["raw_material_inventory"],
        ideal_datasets=["raw_material_inventory", "bom"],
        minimum_fields=["available_stock"],
        supported_scopes=["global", "material"],
        formula_engine="available_stock/daily_consumption",
        fallback_strategy="use_available_columns_for_daily_consumption",
        blockers=["raw_material_inventory_missing"],
        confidence_rule="high_with_stock_and_consumption_signals",
        decision_grade_rule="A_if_coverage_above_target_with_quality_signal",
        output_unit="days",
        output_format="days",
        missing_data_message="Sem base de materia-prima para calcular cobertura.",
    ),
    "rupture_risk": _metric(
        metric_id="rupture_risk",
        display_name="Risco de ruptura",
        category="supply",
        executive_description="Percentual de itens com risco de ruptura por insuficiencia de cobertura.",
        minimum_datasets=["raw_material_inventory"],
        ideal_datasets=["raw_material_inventory", "bom"],
        minimum_fields=["available_stock", "safety_stock"],
        supported_scopes=["global", "material"],
        formula_engine="count(stock_below_safety_or_reorder)",
        fallback_strategy="use_reorder_point_when_safety_missing",
        blockers=["raw_material_inventory_missing"],
        confidence_rule="high_with_safety_or_reorder_fields",
        decision_grade_rule="A_if_low_rupture_risk_with_high_confidence",
        output_unit="%",
        output_format="percent",
        missing_data_message="Sem base de estoque para calcular risco de ruptura.",
    ),
    "excess_risk": _metric(
        metric_id="excess_risk",
        display_name="Risco de excesso",
        category="supply",
        executive_description="Percentual de itens com cobertura excessiva frente ao consumo.",
        minimum_datasets=["raw_material_inventory"],
        ideal_datasets=["raw_material_inventory"],
        minimum_fields=["available_stock"],
        supported_scopes=["global", "material"],
        formula_engine="count(coverage_above_threshold)",
        fallback_strategy="use_stock_vs_safety_ratio_when_consumption_missing",
        blockers=["raw_material_inventory_missing"],
        confidence_rule="medium_to_high_with_consumption_signals",
        decision_grade_rule="A_if_low_excess_risk",
        output_unit="%",
        output_format="percent",
        missing_data_message="Sem base de estoque para calcular risco de excesso.",
    ),
    "mts_incremental_inventory_requirement": _metric(
        metric_id="mts_incremental_inventory_requirement",
        display_name="Investimento incremental MTS",
        category="supply",
        executive_description="Estimativa de investimento adicional em insumos para ampliar politica MTS.",
        minimum_datasets=["production", "sales_orders", "raw_material_inventory", "bom"],
        ideal_datasets=["production", "sales_orders", "raw_material_inventory", "bom"],
        minimum_fields=["produced_quantity", "order_quantity", "qty_per_unit"],
        supported_scopes=["global", "product"],
        formula_engine="positive_gap * bom_unit_cost",
        fallback_strategy="partial_without_full_cost_signal",
        blockers=["production_missing", "sales_orders_missing", "raw_material_inventory_missing", "bom_missing"],
        confidence_rule="high_with_gap_plus_bom_plus_inventory",
        decision_grade_rule="A_or_B_when_cost_signal_complete",
        output_unit="BRL",
        output_format="currency_brl",
        missing_data_message="Sem base integrada (producao, vendas, BOM, estoque MP) para investimento incremental MTS.",
    ),
    # Financeiro executivo
    "projected_revenue": _metric(
        metric_id="projected_revenue",
        display_name="Receita projetada",
        category="financeiro_executivo",
        executive_description="Receita projetada do cenario com fonte documental preferencial.",
        minimum_datasets=["finance_documents"],
        ideal_datasets=["finance_documents", "sales_orders"],
        minimum_fields=[],
        supported_scopes=["global", "scenario"],
        formula_engine="finance_documents_revenue_or_sales_fallback",
        fallback_strategy="sales_orders_price_quantity",
        blockers=["finance_documents_missing"],
        confidence_rule="high_with_structured_finance_docs_medium_with_sales_fallback",
        decision_grade_rule="A_if_ready_high_confidence",
        output_unit="BRL",
        output_format="currency_brl",
        missing_data_message="Sem base financeira documental para projetar receita.",
    ),
    "projected_cogs": _metric(
        metric_id="projected_cogs",
        display_name="COGS projetado",
        category="financeiro_executivo",
        executive_description="COGS projetado com preferencia por fonte documental e separacao de custos quando possivel.",
        minimum_datasets=["finance_documents"],
        ideal_datasets=["finance_documents", "bom", "production"],
        minimum_fields=[],
        supported_scopes=["global", "scenario"],
        formula_engine="finance_documents_cogs_or_bom_cost_fallback",
        fallback_strategy="bom_cost_times_operational_volume",
        blockers=["finance_documents_missing"],
        confidence_rule="high_with_structured_finance_docs_medium_with_bom_fallback",
        decision_grade_rule="A_or_B_when_cost_signal_robust",
        output_unit="BRL",
        output_format="currency_brl",
        missing_data_message="Sem base financeira/custos para projetar COGS.",
    ),
    "contribution_margin": _metric(
        metric_id="contribution_margin",
        display_name="Margem de contribuicao",
        category="financeiro_executivo",
        executive_description="Diferenca entre receita e COGS no escopo selecionado.",
        minimum_datasets=["finance_documents"],
        ideal_datasets=["finance_documents", "sales_orders", "bom", "production"],
        minimum_fields=[],
        supported_scopes=["global", "scenario"],
        formula_engine="projected_revenue - projected_cogs",
        fallback_strategy="use_available_revenue_and_cogs_estimations",
        blockers=["finance_documents_missing"],
        confidence_rule="inherits_revenue_and_cogs_confidence",
        decision_grade_rule="A_or_B_when_margin_quality_is_high",
        output_unit="BRL",
        output_format="currency_brl",
        missing_data_message="Sem base suficiente para calcular margem de contribuicao.",
    ),
    "contribution_margin_pct": _metric(
        metric_id="contribution_margin_pct",
        display_name="Margem de contribuicao (%)",
        category="financeiro_executivo",
        executive_description="Margem percentual sobre a receita projetada.",
        minimum_datasets=["finance_documents"],
        ideal_datasets=["finance_documents", "sales_orders", "bom", "production"],
        minimum_fields=[],
        supported_scopes=["global", "scenario"],
        formula_engine="contribution_margin/projected_revenue",
        fallback_strategy="inherit_margin_fallback",
        blockers=["finance_documents_missing"],
        confidence_rule="inherits_margin_confidence",
        decision_grade_rule="A_or_B_when_margin_pct_stable",
        output_unit="%",
        output_format="percent",
        missing_data_message="Sem base suficiente para calcular margem percentual.",
    ),
    "fg_working_capital": _metric(
        metric_id="fg_working_capital",
        display_name="Capital empatado FG",
        category="financeiro_executivo",
        executive_description="Capital empatado estimado em produtos acabados.",
        minimum_datasets=["finance_documents"],
        ideal_datasets=["finance_documents", "production", "bom"],
        minimum_fields=[],
        supported_scopes=["global", "scenario"],
        formula_engine="finished_goods_cost_exposure",
        fallback_strategy="production_volume_times_bom_unit_cost",
        blockers=["finance_documents_missing"],
        confidence_rule="medium_with_operational_fallback_high_with_financial_rows",
        decision_grade_rule="A_or_B_when_cost_signal_exists",
        output_unit="BRL",
        output_format="currency_brl",
        missing_data_message="Sem base suficiente para estimar capital empatado em FG.",
    ),
    "rm_working_capital": _metric(
        metric_id="rm_working_capital",
        display_name="Capital empatado MP",
        category="financeiro_executivo",
        executive_description="Capital empatado em materia-prima com base em estoque e custo.",
        minimum_datasets=["raw_material_inventory"],
        ideal_datasets=["raw_material_inventory", "finance_documents"],
        minimum_fields=["available_stock"],
        supported_scopes=["global", "scenario", "material"],
        formula_engine="sum(available_stock * unit_cost)",
        fallback_strategy="last_entry_cost_when_unit_cost_missing",
        blockers=["raw_material_inventory_missing"],
        confidence_rule="high_with_cost_and_stock_fields",
        decision_grade_rule="A_if_cost_signal_complete",
        output_unit="USD",
        output_format="currency_usd",
        missing_data_message="Sem base de estoque/custo para capital empatado em MP.",
    ),
    "total_working_capital": _metric(
        metric_id="total_working_capital",
        display_name="Capital empatado total",
        category="financeiro_executivo",
        executive_description="Soma do capital empatado em FG e MP.",
        minimum_datasets=["finance_documents"],
        ideal_datasets=["finance_documents", "raw_material_inventory", "production", "bom"],
        minimum_fields=[],
        supported_scopes=["global", "scenario"],
        formula_engine="fg_working_capital + rm_working_capital",
        fallback_strategy="sum_available_components",
        blockers=["finance_documents_missing"],
        confidence_rule="inherits_component_confidence",
        decision_grade_rule="A_or_B_when_components_ready",
        output_unit="BRL",
        output_format="currency_brl",
        missing_data_message="Sem componentes suficientes para capital empatado total.",
    ),
    "mts_incremental_investment": _metric(
        metric_id="mts_incremental_investment",
        display_name="Investimento incremental MTS (financeiro)",
        category="financeiro_executivo",
        executive_description="Estimativa financeira do investimento incremental para sustentar politica MTS.",
        minimum_datasets=["finance_documents"],
        ideal_datasets=["finance_documents", "sales_orders", "production", "bom", "raw_material_inventory"],
        minimum_fields=[],
        supported_scopes=["global", "scenario", "product"],
        formula_engine="positive_gap(demand-production) * bom_unit_cost",
        fallback_strategy="sales_bom_assumed_gap_20pct_when_production_missing",
        blockers=["finance_documents_missing"],
        confidence_rule="high_with_sales_plus_production_plus_bom",
        decision_grade_rule="A_or_B_when_incremental_cost_signal_is_consistent",
        output_unit="BRL",
        output_format="currency_brl",
        missing_data_message="Sem base integrada para estimar investimento incremental MTS financeiro.",
    ),
    "inventory_carrying_cost": _metric(
        metric_id="inventory_carrying_cost",
        display_name="Custo de carregamento de estoque",
        category="financeiro_executivo",
        executive_description="Custo anual estimado de carregamento sobre o capital empatado.",
        minimum_datasets=["finance_documents"],
        ideal_datasets=["finance_documents", "raw_material_inventory", "production", "bom"],
        minimum_fields=[],
        supported_scopes=["global", "scenario"],
        formula_engine="total_working_capital * carrying_rate",
        fallback_strategy="default_carrying_rate_when_not_explicit",
        blockers=["finance_documents_missing"],
        confidence_rule="inherits_total_working_capital_confidence",
        decision_grade_rule="A_or_B_when_base_capital_available",
        output_unit="BRL",
        output_format="currency_brl",
        missing_data_message="Sem base para estimar custo de carregamento.",
    ),
    "scenario_delta_financial": _metric(
        metric_id="scenario_delta_financial",
        display_name="Delta financeiro do cenario",
        category="financeiro_executivo",
        executive_description="Variação financeira do cenario selecionado versus cenario base.",
        minimum_datasets=["finance_documents"],
        ideal_datasets=["finance_documents", "sales_orders", "raw_material_inventory", "bom", "production"],
        minimum_fields=[],
        supported_scopes=["scenario"],
        formula_engine="scenario(selected) - scenario(base)",
        fallback_strategy="heuristic_scenario_multipliers",
        blockers=["finance_documents_missing"],
        confidence_rule="high_with_structured_finance_docs_medium_with_heuristics",
        decision_grade_rule="A_or_B_when_scenario_assumptions_transparent",
        output_unit="BRL",
        output_format="currency_brl",
        missing_data_message="Sem base para comparar delta financeiro entre cenarios.",
    ),
}


def list_metric_registry_entries() -> list[dict[str, Any]]:
    entries = [deepcopy(metric) for metric in METRIC_REGISTRY.values()]
    return sorted(entries, key=lambda item: str(item["metric_id"]))


def get_metric_registry_entry(metric_id: str) -> dict[str, Any]:
    if metric_id not in METRIC_REGISTRY:
        raise KeyError(metric_id)
    return deepcopy(METRIC_REGISTRY[metric_id])


def get_metric_registry_payload() -> dict[str, Any]:
    return {
        "version": METRIC_REGISTRY_V1_VERSION,
        "metrics": list_metric_registry_entries(),
    }
